### ISSUE TITLE
05, 06, 07, and 08 throw errors

### ISSUE THREAD

**Issue by JWSchaefer** [digiLab-ai/twinLab-Demos#19]
Multiple errors thrown across these scripts using deployed version of twinlab.

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
twinlab = "^1.4"
jupyter = "^1.0.0"
numpy = "^1.24.2"
matplotlib = "^3.7.1"
pandas = "^1.5.3"
tinyda = "^0.9.13"

**Comment by jacantwell** [comment]
The error on notebook five is because fidelity is not yet exposed to the python client in the prod branch. This is raised in twinlab issue #476

**Comment by jacantwell** [comment]
Notebook 6 doesnt work because prod is broken

**Comment by jacantwell** [comment]
Notebook 7 is sorted

**Comment by jacantwell** [comment]
Notebook 8 failes because solve_inverse is still not in prod
